services:
  pergamo:
    container_name: "pergamo"
    image: "pergamo"
    restart: "always"
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    volumes:
      - "./data:/usr/src/app/data"
    env_file:
      - ".env"